# Generated by Django 2.0.7 on 2018-07-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mustbuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200, verbose_name='图片地址')),
                ('name', models.CharField(max_length=25, verbose_name='书名')),
                ('bookid', models.CharField(max_length=20, verbose_name='书id')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True, verbose_name='用户账号')),
                ('userPasswd', models.CharField(max_length=20, verbose_name='密码')),
                ('userName', models.CharField(max_length=20, verbose_name='昵称')),
                ('userPhone', models.CharField(max_length=20, verbose_name='手机号')),
                ('userAdderss', models.CharField(max_length=100, verbose_name='地址')),
                ('userImg', models.CharField(max_length=150, verbose_name='头像路径')),
                ('userRank', models.IntegerField(default=0, verbose_name='等级')),
                ('userToken', models.CharField(max_length=50, verbose_name='touken验证值')),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=150, verbose_name='图片地址')),
                ('name', models.CharField(max_length=25, verbose_name='书名')),
                ('bookid', models.CharField(max_length=10, verbose_name='书id')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
        ),
    ]
