# Generated by Django 2.0.7 on 2018-07-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200, verbose_name='图片地址')),
                ('name', models.CharField(max_length=25, verbose_name='栏目名')),
                ('url', models.CharField(max_length=200, verbose_name='栏目地址')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, verbose_name='订单时间')),
                ('remarks', models.CharField(default=None, max_length=200, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
        ),
    ]
