# Generated by Django 2.0.7 on 2018-07-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='书名')),
                ('bookid', models.CharField(max_length=20, verbose_name='书id')),
                ('img', models.CharField(max_length=200, verbose_name='图片地址')),
                ('price', models.FloatField(max_length=20, verbose_name='书价格')),
                ('mprice', models.FloatField(max_length=20, verbose_name='书市场价')),
                ('info', models.CharField(max_length=250, verbose_name='书详细介绍')),
                ('nums', models.IntegerField(verbose_name='书库存')),
                ('salesnums', models.IntegerField(verbose_name='销量')),
                ('iswonderf', models.BooleanField(default=False, verbose_name='是否精选')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20, verbose_name='书类别名')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booknum', models.IntegerField(verbose_name='书数量')),
                ('isChose', models.BooleanField(default=False, verbose_name='是否选择')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myApp.Book', verbose_name='书')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='book',
            name='booktype',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myApp.BookType', verbose_name='书类别'),
        ),
    ]
